name: task_manager
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # Service Locator
  get_it: ^7.6.0
  # bloc for state management
  flutter_bloc: ^8.1.3
  # value equality
  equatable: ^2.0.5
  # functional programming thingies
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^1.0.0+1
  http: any
  # Local Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  # Ui stuff
  flutter_background_service: ^3.0.1
  flutter_local_notifications: ^15.1.0+1
  flutter_datetime_picker_plus: ^2.0.1
  date_format: ^2.0.7
  floating_bottom_navigation_bar: ^1.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: any
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
